FROM --platform=$BUILDPLATFORM golang:1.19.2 as builder

WORKDIR /shifudriver

COPY modbus-driver/* .

RUN go mod download -x

RUN CGO_ENABLED=0 GOOS=$TARGETOS GOARCH=$TARGETARCH go build -a -o /output/driver driver.go 

FROM gcr.io/distroless/static-debian11
WORKDIR /
COPY --from=builder /output/driver driver

# Command to run the executable
USER 65532:65532
ENTRYPOINT ["/driver"]