--- #telemetry_service.yaml
apiVersion: shifu.edgenesis.io/v1alpha1
kind: TelemetryService
metadata:
  name: push-endpoint-1
  namespace: devices
spec:
  telemetrySeriveEndpoint: http://telemetryservice.shifu-service.svc.cluster.local
  serviceSettings:
    SQLSetting:
      serverAddress: 192.168.0.37:6041 # edit it to your your IP
      username: root
      secret: taosdata
      dbName: shifu
      dbTable: testSubTable
      dbtype: TDEngine
